#!/usr/bin/env python3
"""Generate the ADR atlas overview — a decision graph + status table read
straight from the ADR files, so it stays current as ADRs are added.

    linux/scripts/adr-atlas-graph.py            # write docs/linux-port/adr/_overview.md
    linux/scripts/adr-atlas-graph.py --check    # exit 1 if _overview.md is stale

Each ADR (NNNN-*.md) contributes a node coloured by Status (Accepted /
Proposed / Rejected / Superseded). Edges come from cross-references between
ADRs in the body (an ADR that mentions another NNNN links to it) and from
"Superseded by NNNN". The graph is the value an ADR *atlas* adds over a
folder of markdown: the decision landscape at a glance.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ADR = os.path.join(ROOT, "docs", "linux-port", "adr")
OUT = os.path.join(ADR, "_overview.md")

STATUS_CLASS = {           # status keyword → (mermaid class, css fill/stroke)
    "accepted": ("accepted", "#2ea04322,stroke:#2ea043"),
    "proposed": ("proposed", "#d2992222,stroke:#d29922"),
    "rejected": ("rejected", "#f8514922,stroke:#f85149"),
    "superseded": ("superseded", "#6e768166,stroke:#6e7681"),
}


def parse():
    adrs = {}
    for fn in sorted(os.listdir(ADR)):
        m = re.match(r"^(\d{4})-(.+)\.md$", fn)
        if not m:
            continue
        num = m.group(1)
        text = open(os.path.join(ADR, fn)).read()
        title = ""
        h1 = re.search(r"^#\s*\d{4}\s*[—-]\s*(.+)$", text, re.M)
        if h1:
            title = h1.group(1).strip()
        sm = re.search(r"^-?\s*\*\*Status:\*\*\s*(\w+)", text, re.M)
        status = (sm.group(1).lower() if sm else "proposed")
        # cross-references to other ADRs (4-digit numbers that aren't self)
        refs = set(re.findall(r"\b(\d{4})\b", text)) - {num}
        refs = {r for r in refs if r != num}
        adrs[num] = {"file": fn, "title": title, "status": status, "refs": refs}
    return adrs


def build_overview(adrs):
    lines = []
    lines.append("# ADR atlas — the decision landscape\n")
    lines.append("Generated by `linux/scripts/adr-atlas-graph.py` from the ADR "
                 "files — re-run it when you add or re-status an ADR. Nodes are "
                 "coloured by status; edges are cross-references between records.\n")
    lines.append("```mermaid")
    lines.append("flowchart TD")
    for num, a in adrs.items():
        label = a["title"] if len(a["title"]) <= 46 else a["title"][:44] + "…"
        lines.append(f'    n{num}["{num}<br/>{label}<br/><i>{a["status"]}</i>"]')
    # edges: only where BOTH ends are real ADRs, dedup A->B / B->A to one link
    seen = set()
    for num, a in adrs.items():
        for r in sorted(a["refs"]):
            if r not in adrs:
                continue
            key = tuple(sorted((num, r)))
            if key in seen:
                continue
            seen.add(key)
            lines.append(f"    n{num} --- n{r}")
    for num, a in adrs.items():
        cls = STATUS_CLASS.get(a["status"], STATUS_CLASS["proposed"])
        lines.append(f"    style n{num} fill:{cls[1]}")
    lines.append("```\n")
    # status table
    lines.append("| # | Decision | Status |")
    lines.append("|---|---|---|")
    for num, a in adrs.items():
        lines.append(f"| [{num}]({a['file']}) | {a['title']} | {a['status']} |")
    lines.append("")
    lines.append("Legend: 🟩 accepted · 🟨 proposed · 🟥 rejected · ⬜ superseded. "
                 "Full record behind each node — pick it from the sidebar.")
    return "\n".join(lines) + "\n"


def main():
    adrs = parse()
    content = build_overview(adrs)
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != content:
            sys.exit("adr-atlas-graph: _overview.md is stale — re-run without --check")
        print("adr overview up to date")
        return
    open(OUT, "w").write(content)
    print(f"wrote {OUT} ({len(adrs)} ADRs)")


if __name__ == "__main__":
    main()
